<b>Partlist exported from C:/Users/pimen/Documents/EAGLE/projects/Catch_the_light_Phase_2 Rev A/Schematic.sch at 11/7/2019 1:49 PM</b>
<p>
<table>
<tr><td><b>Part</b></td><td><b>Value</b></td><td><b>Device</b></td><td><b>Package</b></td><td><b>Description</b></td><td><b>AVAILABILITY</b></td><td><b>DESCRIPTION</b></td><td><b>DIGI-KEY_PART_NUMBER</b></td><td><b>DIGI-KEY_PURCHASE_URL</b></td><td><b>MF</b></td><td><b>MP</b></td><td><b>MPN</b></td><td><b>OC_FARNELL</b></td><td><b>OC_NEWARK</b></td><td><b>PACKAGE</b></td><td><b>POPULARITY</b></td><td><b>PRICE</b></td><td><b>SPICEPREFIX</b></td></tr>
<tr><td>BATT</td><td></td><td>BC-2003SMD</td><td>BC-2003</td><td>Batter Holder for the following:</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>C1</td><td>100n</td><td>C-USC0805</td><td>C0805</td><td>CAPACITOR, American symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>63</td><td></td><td>C</td></tr>
<tr><td>C2</td><td>100n</td><td>C-USC0805</td><td>C0805</td><td>CAPACITOR, American symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>63</td><td></td><td>C</td></tr>
<tr><td>C3</td><td>100n</td><td>C-USC0805</td><td>C0805</td><td>CAPACITOR, American symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>63</td><td></td><td>C</td></tr>
<tr><td>C4</td><td>100n</td><td>C-USC0805</td><td>C0805</td><td>CAPACITOR, American symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>63</td><td></td><td>C</td></tr>
<tr><td>C5</td><td>100n</td><td>C-USC0805</td><td>C0805</td><td>CAPACITOR, American symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>63</td><td></td><td>C</td></tr>
<tr><td>C6</td><td>100n</td><td>C-USC0805</td><td>C0805</td><td>CAPACITOR, American symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>63</td><td></td><td>C</td></tr>
<tr><td>ISP1</td><td>AVRISP-6</td><td>AVRISP-6</td><td>AVRISP</td><td>AVR ISP HEADER</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>LED1</td><td>Green</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED2</td><td>Blue</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED3</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED4</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED5</td><td></td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED6</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED7</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED8</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED9</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED10</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED11</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED12</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED13</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED14</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED15</td><td>Red</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>LED16</td><td>Blue</td><td>LEDCHIP-LED0805</td><td>CHIP-LED0805</td><td>LED</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>68</td><td></td><td></td></tr>
<tr><td>Q1</td><td></td><td>CRYSTALHC49UP</td><td>HC49UP</td><td>CRYSTAL</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>unknown</td><td>unknown</td><td></td><td>19</td><td></td><td></td></tr>
<tr><td>Q2</td><td>SI2323DS</td><td>SI2323DS</td><td>SOT23</td><td>P-Channel MOSFET</td><td>Unavailable</td><td> </td><td></td><td></td><td>Vishay Siliconix</td><td>SI2323DS</td><td></td><td></td><td></td><td>SOT-23-3 Vishay</td><td></td><td>None</td><td></td></tr>
<tr><td>R1</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R2</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R3</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R4</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R5</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R6</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R7</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R8</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R9</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R10</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R11</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R12</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R13</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R14</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R15</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R16</td><td>1.5k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R17</td><td>10k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R18</td><td>10k</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R19</td><td>0</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>R20</td><td>0</td><td>R-EU_R0805</td><td>R0805</td><td>RESISTOR, European symbol</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td>86</td><td></td><td>R</td></tr>
<tr><td>S2</td><td>DTSM-6</td><td>DTSM-6</td><td>DTSM-6</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>TC1</td><td>TC2030-IDC-NL</td><td>TC2030-IDC-NL</td><td>TC2030-IDC-NL</td><td>Tag-Connect In Circuit Programming & Debug Cable 6 Pin</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$1</td><td>TEST_POINT</td><td>TEST_POINT</td><td>TEST_POINT</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$2</td><td>TEST_POINT</td><td>TEST_POINT</td><td>TEST_POINT</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$3</td><td>TEST_POINT</td><td>TEST_POINT</td><td>TEST_POINT</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$4</td><td>TEST_POINT</td><td>TEST_POINT</td><td>TEST_POINT</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$5</td><td>TEST_POINT</td><td>TEST_POINT</td><td>TEST_POINT</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$6</td><td>PINHEADER</td><td>PINHEADER</td><td>HEADERPIN</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$7</td><td>FIDUCIAL</td><td>FIDUCIAL</td><td>FIDUCIAL_1MM</td><td>For use by pick and place machines to calibrate the vision/machine, 1mm</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$8</td><td>FIDUCIAL</td><td>FIDUCIAL</td><td>FIDUCIAL_1MM</td><td>For use by pick and place machines to calibrate the vision/machine, 1mm</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U$9</td><td>FIDUCIAL</td><td>FIDUCIAL</td><td>FIDUCIAL_1MM</td><td>For use by pick and place machines to calibrate the vision/machine, 1mm</td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td><td></td></tr>
<tr><td>U1</td><td>ATMEGA328PB-AUR</td><td>ATMEGA328PB-AUR</td><td>QFP80P900X900X120-32N</td><td>ATmega Series 20 MHz 32 KB Flash 2 KB SRAM 8-Bit Microcontroller - TQFP-32</td><td></td><td> AVR microcontroller</td><td> EEPROM: 1024B</td><td> SRAM: 2kB</td><td> Flash: 32kB</td><td> TQFP32 </td><td>ATMEGA328PB-AURCT-ND</td><td>https://www.digikey.com/product-detail/en/microchip-technology/ATMEGA328PB-AUR/ATMEGA328PB-AURCT-ND/5722706?utm_source=snapeda&utm_medium=aggregator&utm_campaign=symbol</td><td>Microchip</td><td>ATMEGA328PB-AUR</td><td></td><td></td><td></td></tr>
</table>
